- id: doi:10.1111/resp.14857
  image: https://onlinelibrary.wiley.com/cms/asset/b1d6724c-77f4-447c-943f-a6a824cf64e9/resp.v30.1.cover.jpg
  
- id: doi:10.1101/2025.04.15.648833
  image: https://www.biorxiv.org/sites/default/files/biorxiv_logo_homepage.png
  
- id: doi:10.1038/s41586-024-07377-1
  image: https://media.springernature.com/w440/springer-static/cover-hires/journal/41586/629/8013

- id: doi:10.1165/rcmb.2023-0169ED
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/ajrcmb/Issue/69/3/1/m_cover.gif?Expires=1779837019&Signature=3ONcfHuF4B5aeND0JhFpTSHFlY-3Pl1UckAnev4lftwzvA9R6vwiG2oFBv51~YQovdFFkUQM0qKFlVECnK3C9p7~T969KDbDh2PCV7mntZMaBvcum3ZFID21sShCn0qbAY4MNmt80KKwtH0K7aMOncgC4ZorHv6BRVFDCDzOi9wtdrVl-7-NPf~so-c08FzxHjtVGFBelVIcf0IWFg9NXtjYr5JIkJ7stv3ao8RKJaWW3JZwCAxQZJ0ZR2tFD4FkCg8WpuRb8Pc-~xMEl8r8LyMHIYz6zdrrTWh66jjnqR1vbb5VMSF8WtOnVKyEPW6Eo7af8-1gS8C4Yxp7DhTs3g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  
- id: doi:10.1146/annurev-pathol-042420-094031
  image: https://www.annualreviews.org/docserver/fulltext/pathmechdis-184x258.png

- id: doi:10.1073/pnas.1604905113
  image: https://www.pnas.org/cms/asset/6a104d88-b8d3-45e2-a0d9-505d2f929506/pnas.2016.113.issue-19.largecover.png

- id: doi:10.1126/science.aad5589
  image="images/science.jpg"

- id: doi:10.7554/eLife.84375
  image: https://elifesciences.org/assets/patterns/img/patterns/organisms/elife-logo-xs.5a3c8c68.svg
